{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fq.sdk",
    "module": "buychannel",
    "version": "1.1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "buychannel-1.1.2.aar",
          "url": "buychannel-1.1.2.aar",
          "size": 39936,
          "sha512": "77c403348a0c82a6b8102230fcc932edd0ddfbfdb5193eb7947320690e6dbc5fa8f1870ce4e91ba406f1d598b751aec3056b20bedfeb02963539ddd225ded708",
          "sha256": "0047f5ffc522cd8287cffce114bc9be1abae0e9e4344df297923f61b39944132",
          "sha1": "07c115805a905e07e8328191567a497393b9619b",
          "md5": "32fb0aad9f0240a0aecb195007575c6a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "af-android-sdk",
          "version": {
            "requires": "6.12.1"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "buychannel-1.1.2.aar",
          "url": "buychannel-1.1.2.aar",
          "size": 39936,
          "sha512": "77c403348a0c82a6b8102230fcc932edd0ddfbfdb5193eb7947320690e6dbc5fa8f1870ce4e91ba406f1d598b751aec3056b20bedfeb02963539ddd225ded708",
          "sha256": "0047f5ffc522cd8287cffce114bc9be1abae0e9e4344df297923f61b39944132",
          "sha1": "07c115805a905e07e8328191567a497393b9619b",
          "md5": "32fb0aad9f0240a0aecb195007575c6a"
        }
      ]
    }
  ]
}
