{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fq.sdk",
    "module": "statistic",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "statistic-1.1.3.aar",
          "url": "statistic-1.1.3.aar",
          "size": 220076,
          "sha512": "67fe32f24253e28c158018fe07eb1bba4626e2b49ad1b258f094209097765590d91fff0cc9f2e76835ac2e82ee4055cf764a74ff16f3333834e8b71bda976115",
          "sha256": "01f978517908231f24e64e2c90b055c8214e1bbc9cb9a571bd26f16fc45b3388",
          "sha1": "8c3e4b20340d2ac55307a8e6ab420d16a55ba2a3",
          "md5": "f8be087e21e875ac2968ad16cbe04310"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "statistic-1.1.3.aar",
          "url": "statistic-1.1.3.aar",
          "size": 220076,
          "sha512": "67fe32f24253e28c158018fe07eb1bba4626e2b49ad1b258f094209097765590d91fff0cc9f2e76835ac2e82ee4055cf764a74ff16f3333834e8b71bda976115",
          "sha256": "01f978517908231f24e64e2c90b055c8214e1bbc9cb9a571bd26f16fc45b3388",
          "sha1": "8c3e4b20340d2ac55307a8e6ab420d16a55ba2a3",
          "md5": "f8be087e21e875ac2968ad16cbe04310"
        }
      ]
    }
  ]
}
