{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fq.sdk",
    "module": "statistic",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "statistic-1.1.3.aar",
          "url": "statistic-1.1.3.aar",
          "size": 236768,
          "sha512": "ef93b1486edde1b5daa72ce0dd62f224885a5de1f200b4f930758f95bea98c6bb39773f54c659decac91c5ce448d7793754953bb1eb040b6e6678db60a3a8059",
          "sha256": "53a907d98c1ac94f75bacd7493a6c83f15aea9e82e560d822736410e11d857b6",
          "sha1": "2961019a9a53637177fba40ea01f1a70180fb6ba",
          "md5": "ee9c0159e627d50cdf2a3857fdacbc77"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "statistic-1.1.3.aar",
          "url": "statistic-1.1.3.aar",
          "size": 236768,
          "sha512": "ef93b1486edde1b5daa72ce0dd62f224885a5de1f200b4f930758f95bea98c6bb39773f54c659decac91c5ce448d7793754953bb1eb040b6e6678db60a3a8059",
          "sha256": "53a907d98c1ac94f75bacd7493a6c83f15aea9e82e560d822736410e11d857b6",
          "sha1": "2961019a9a53637177fba40ea01f1a70180fb6ba",
          "md5": "ee9c0159e627d50cdf2a3857fdacbc77"
        }
      ]
    }
  ]
}
