{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fq.sdk",
    "module": "buychannel",
    "version": "1.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "buychannel-1.0.6.aar",
          "url": "buychannel-1.0.6.aar",
          "size": 35682,
          "sha512": "9518c61514207b60bc0e444e2b289de9d434b4560119f8e555bcbfdac7a0c75260dd049147c205c46de839782523d9f979fe7745ddba587fb58321c2c44d2a22",
          "sha256": "0f837f7fd813409a92b7a3910153b56ceff016a3333c74e815892780f3c67700",
          "sha1": "c1ab06c9d7fa37461e0a7982fc3cb734b06f9caf",
          "md5": "b51a2be8beb43fe1b79bbfec18df2eb4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "af-android-sdk",
          "version": {
            "requires": "6.12.1"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "buychannel-1.0.6.aar",
          "url": "buychannel-1.0.6.aar",
          "size": 35682,
          "sha512": "9518c61514207b60bc0e444e2b289de9d434b4560119f8e555bcbfdac7a0c75260dd049147c205c46de839782523d9f979fe7745ddba587fb58321c2c44d2a22",
          "sha256": "0f837f7fd813409a92b7a3910153b56ceff016a3333c74e815892780f3c67700",
          "sha1": "c1ab06c9d7fa37461e0a7982fc3cb734b06f9caf",
          "md5": "b51a2be8beb43fe1b79bbfec18df2eb4"
        }
      ]
    }
  ]
}
