{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fq.sdk",
    "module": "buychannel",
    "version": "1.0.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "buychannel-1.0.9.aar",
          "url": "buychannel-1.0.9.aar",
          "size": 39905,
          "sha512": "bdf2be5bd094d2dc2ac4a47fb5973db25f50e7b824f821de8fcd55d1f2e55bf54adb99093a8ea9d39ef81003c90303ef7c1043815db10bee4e35ec4ddcaa4ed6",
          "sha256": "47f647ee0dbb72fe52df4f036bb950b724014b4b274fa53691f346f349aef497",
          "sha1": "a97f563a00e5a7963159886ba9da83d7f2f8d5c0",
          "md5": "22baf2d4678945c4a54ad8f46e27e2d7"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "af-android-sdk",
          "version": {
            "requires": "6.12.1"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "buychannel-1.0.9.aar",
          "url": "buychannel-1.0.9.aar",
          "size": 39905,
          "sha512": "bdf2be5bd094d2dc2ac4a47fb5973db25f50e7b824f821de8fcd55d1f2e55bf54adb99093a8ea9d39ef81003c90303ef7c1043815db10bee4e35ec4ddcaa4ed6",
          "sha256": "47f647ee0dbb72fe52df4f036bb950b724014b4b274fa53691f346f349aef497",
          "sha1": "a97f563a00e5a7963159886ba9da83d7f2f8d5c0",
          "md5": "22baf2d4678945c4a54ad8f46e27e2d7"
        }
      ]
    }
  ]
}
