{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fq.sdk",
    "module": "buychannel",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "buychannel-1.1.3.aar",
          "url": "buychannel-1.1.3.aar",
          "size": 43205,
          "sha512": "9cae1b4306b93b31ac85893a47a5efd14b422931a8e1e796f98fb67067f9e6d9881b2ae0624ff8084f233ae6cd9004e91adbdb713c3f3b0d0882ee9d82c5d0b3",
          "sha256": "f2cd96134b8848643215a3f3e0e86c35e083f503e748e06160251fe2e11c05ed",
          "sha1": "028be3609f88091c1fa1adc9cd8f206f3837683a",
          "md5": "f1fe0f4a2d51e138cc8231d85edec9ae"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          },
          "excludes": [
            {
              "group": "com.android.support",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "af-android-sdk",
          "version": {
            "requires": "6.12.1"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "buychannel-1.1.3.aar",
          "url": "buychannel-1.1.3.aar",
          "size": 43205,
          "sha512": "9cae1b4306b93b31ac85893a47a5efd14b422931a8e1e796f98fb67067f9e6d9881b2ae0624ff8084f233ae6cd9004e91adbdb713c3f3b0d0882ee9d82c5d0b3",
          "sha256": "f2cd96134b8848643215a3f3e0e86c35e083f503e748e06160251fe2e11c05ed",
          "sha1": "028be3609f88091c1fa1adc9cd8f206f3837683a",
          "md5": "f1fe0f4a2d51e138cc8231d85edec9ae"
        }
      ]
    }
  ]
}
