{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fq.sdk",
    "module": "buychannel",
    "version": "1.1.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "buychannel-1.1.5.aar",
          "url": "buychannel-1.1.5.aar",
          "size": 72140,
          "sha512": "402aefcefafb8d06a331f0e0765e655be1dc613e1226f6b68749fc49463e46d08c595ab50b5498fd54f6528428624e5d24e6c0b02259024594fd319f6032eb35",
          "sha256": "936b4a51d27b3ae9d5a8d856d5758c84e4307afec0c3ff8f45ac2722493640bf",
          "sha1": "42133193f9d6c565475363d10ec5130bd1517838",
          "md5": "5c8386eff7ee1e3c11dc8dc7ed03b6b3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.10.0"
          },
          "excludes": [
            {
              "group": "com.android.support",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "af-android-sdk",
          "version": {
            "requires": "6.15.2"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "buychannel-1.1.5.aar",
          "url": "buychannel-1.1.5.aar",
          "size": 72140,
          "sha512": "402aefcefafb8d06a331f0e0765e655be1dc613e1226f6b68749fc49463e46d08c595ab50b5498fd54f6528428624e5d24e6c0b02259024594fd319f6032eb35",
          "sha256": "936b4a51d27b3ae9d5a8d856d5758c84e4307afec0c3ff8f45ac2722493640bf",
          "sha1": "42133193f9d6c565475363d10ec5130bd1517838",
          "md5": "5c8386eff7ee1e3c11dc8dc7ed03b6b3"
        }
      ]
    }
  ]
}
