{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fq.sdk",
    "module": "buychannel",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "buychannel-1.0.7.aar",
          "url": "buychannel-1.0.7.aar",
          "size": 39881,
          "sha512": "4d06ac590b2b89923ac8a0febe096f1c083fce90ffbcec001d167eb20a4676165d0d08f6dc97ebbb7823b192ae1a12107bd0a1d1427317f52662b974a656d35e",
          "sha256": "db8e10c530b96d5d562caabc63af53098b6c629eafc20465a1fdab61c68393f5",
          "sha1": "c3bd305da48dc38b91904ac1fbebbc146cfd43c0",
          "md5": "1beb3680f753ee3ba0633075e1e3a060"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.appsflyer",
          "module": "af-android-sdk",
          "version": {
            "requires": "6.12.1"
          }
        },
        {
          "group": "com.android.installreferrer",
          "module": "installreferrer",
          "version": {
            "requires": "2.2"
          }
        }
      ],
      "files": [
        {
          "name": "buychannel-1.0.7.aar",
          "url": "buychannel-1.0.7.aar",
          "size": 39881,
          "sha512": "4d06ac590b2b89923ac8a0febe096f1c083fce90ffbcec001d167eb20a4676165d0d08f6dc97ebbb7823b192ae1a12107bd0a1d1427317f52662b974a656d35e",
          "sha256": "db8e10c530b96d5d562caabc63af53098b6c629eafc20465a1fdab61c68393f5",
          "sha1": "c3bd305da48dc38b91904ac1fbebbc146cfd43c0",
          "md5": "1beb3680f753ee3ba0633075e1e3a060"
        }
      ]
    }
  ]
}
